(ns pozn-adaptive.menu-db)

(def menu-items-vector
  [{:description
                    "Америка́но или  «кофе по-американски» —зерновой кофе,разбавленный горячей водой.",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name "Американо",
    :weight "120мл",
    :id 5487,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Американо ",
    :price 70}
   {:description
                    "Тёртый сыр с чесноком завернутый в обжаренный во фритюре тонкий пласт баклажана",
    :tags "",
    :ings
                    "баклажан, сыр, чеснок, майонез. Украшение: помидор, лист салата.",
    :group "Салаты",
    :c_time "10",
    :short_name "Баклажаны с сыром",
    :weight "90/30",
    :id 3802,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Баклажаны с сыром и чесноком",
    :price 74}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name "Кит Кат 58гр",
    :weight "58",
    :id 3742,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Батончик Кит Кат 58гр ",
    :price 0}
   {:description "Обжаренная говяжья печень с луком в сливочном соусе",
    :tags "",
    :ings
                 "печень говяжья, сливки, лук, соль, перец. Украшение: помидор, огурец, лист салата.",
    :group "Горячее",
    :c_time "20",
    :short_name "Бефстроганов",
    :weight "180/30",
    :id 3791,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Бефстроганов из печени",
    :price 110}
   {:description "Запечённая котлета из рубленной говядины с яичницей.",
    :tags "",
    :ings
                 "Говядина,сало,лук,соль,перец,яйцо,укроп. Украшение: помидор, огурец, лист салата,укроп.",
    :group "Горячее",
    :c_time "20",
    :short_name "Бифштекс",
    :weight "140/40/30",
    :id 3834,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Бифштекс с яйцом ",
    :price 150}
   {:description
                    "Два блина, фаршированные говяжьим фаршем в томатном соусе",
    :tags "",
    :ings
                    "Блины: яйцо, мука, молоко, вода, соль, сахар, сода. Начинка: говяжий фарш, лук, томатный соус, соль, перец",
    :group "Хиты",
    :c_time "20",
    :short_name "Блинчики Болоньезе",
    :weight "180",
    :id 3817,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Блинчики Болоньезе ",
    :price 95}
   {:description
                    "Два блина, фаршированные  ветчиной и расплавленным сыром.",
    :tags "",
    :ings
                    "Блины: яйцо, мука, молоко, вода, соль, сахар, сода. Начинка: ветчина,мягкий сыр.",
    :group "Хиты",
    :c_time "20",
    :short_name " Блинчики с ветчиной и сыром ",
    :weight "180",
    :id 3819,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Блинчики с ветчиной и сыром ",
    :price 95}
   {:description
                    "Два блина, фаршированные куриным филе с луком и шампиньонами в сливочном соусе.",
    :tags "",
    :ings
                    "Блины: яйцо, мука, молоко, вода, соль, сахар, сода. Начинка: куриное филе, лук, шампиньоны, сливки.",
    :group "Хиты",
    :c_time "20",
    :short_name " Блинчики с курицей и грибами ",
    :weight "180",
    :id 3818,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Блинчики с курицей и грибами ",
    :price 95}
   {:description
                    "Три блина, обжаренные до румяной корочки на сливочном масле.",
    :tags "",
    :ings "яйцо, мука, молоко, вода, соль, сахар, сода",
    :group "Хиты",
    :c_time "20",
    :short_name " Блины (3шт) ",
    :weight "150",
    :id 3816,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Блины (3шт) ",
    :price 45}
   {:description
                    "Классический борщ на наваристом говяжьем бульоне с кусочками говядины, заправленный на выбор гостя сметаной или майонезом.",
    :tags "",
    :ings
                    "говядина, свекла, капуста, морковь, лук, чеснок, соль, перец, лавровый лист, сметана или майонез",
    :group "Супы",
    :c_time "15",
    :short_name " Борщ ",
    :weight "330",
    :id 3792,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Борщ ",
    :price 98}
   {:description
                    "Классический борщ на наваристом говяжьем бульоне с кусочками говядины, заправленный на выбор гостя сметаной или майонезом.",
    :tags "",
    :ings
                    "говядина, свекла, капуста, морковь, лук, чеснок, соль, перец, лавровый лист, сметана или майонез",
    :group "Супы",
    :c_time "15",
    :short_name " Борщ с майонезом ",
    :weight "330/20",
    :id 3793,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Борщ с майонезом ",
    :price 98}
   {:description
                    "Классический борщ на наваристом говяжьем бульоне с кусочками говядины, заправленный на выбор гостя сметаной или майонезом.",
    :tags "",
    :ings
                    "говядина, свекла, капуста, морковь, лук, чеснок, соль, перец, лавровый лист, сметана или майонез",
    :group "Супы",
    :c_time "15",
    :short_name " Борщ со сметаной ",
    :weight "330/20",
    :id 3794,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Борщ со сметаной ",
    :price 98}
   {:description
                    "Наваристый бульон из баранины с картофелем и бараньими косточками с мясом.",
    :tags "",
    :ings
                    "баранина, картофель, морковь, лук, укроп, перец, соль, лавровый лист",
    :group "Супы",
    :c_time "15",
    :short_name " Бухлер ",
    :weight "350",
    :id 3801,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Бухлер ",
    :price 150}
   {:description
                    "Фирменные вареники ручной лепки с вишнёвым вареньем,обжаренные во фритюре. Подаются со сметаной.",
    :tags "",
    :ings "",
    :group "Хиты",
    :c_time "20",
    :short_name " Вареники с вишней во фритюре",
    :weight "180/50",
    :id 3820,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "4",
    :full_name " Вареники с вишней во фритюре",
    :price 110}
   {:description
                    "Фирменные вареники ручной лепки с отварным картофелем,лучком и грибами,обжаренные во фритюре. Подаются со сметаной.",
    :tags "",
    :ings "",
    :group "Хиты",
    :c_time "20",
    :short_name " Вареники с картофелем и грибами во фритюре ",
    :weight "180/50",
    :id 3821,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Вареники с картофелем и грибами во фритюре ",
    :price 110}
   {:description
                    "Фирменные отварные вареники ручной лепки с отварным картофелем и грибами. Подаются со сметаной.",
    :tags "",
    :ings "",
    :group "Хиты",
    :c_time "20",
    :short_name " Вареники с картошкой и грибами вареные ",
    :weight "180/50",
    :id 3823,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Вареники с картошкой и грибами вареные ",
    :price 90}
   {:description
                    "Фирменные вареники ручной лепки с клубничным вареньем,обжаренные во фритюре. Подаются со сметаной.",
    :tags "",
    :ings "",
    :group "Хиты",
    :c_time "20",
    :short_name " Вареники с клубникой во фритюре ",
    :weight "180/50",
    :id 3822,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "4",
    :full_name " Вареники с клубникой во фритюре ",
    :price 110}
   {:description
                    "Фирменные отварные вареники ручной лепки с творогом. Подаются со сметаной.",
    :tags "",
    :ings "",
    :group "Хиты",
    :c_time "20",
    :short_name " Вареники с творогом ",
    :weight "180/50",
    :id 3824,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Вареники с творогом ",
    :price 110}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name "Вино бокалом белое п/сладкое 150мл",
    :weight "150",
    :id 7241,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Вино Барон де Сад бел. п/сл. 150мл. ",
    :price 80}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name "Вино бокалом красное п/сладкое 150мл",
    :weight "150",
    :id 7242,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Вино Барон де Сад кр. п/сл. 150мл.",
    :price 80}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Виски Fat boy 50мл. ",
    :weight "50",
    :id 7237,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Виски Fat boy 50мл. ",
    :price 130}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Водка Хортиця 0,5л. ",
    :weight "0,5л",
    :id 7235,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Водка Хортиця 0,5л. ",
    :price 500}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Водка Хортиця 50мл.",
    :weight "50",
    :id 7236,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Водка Хортиця 50мл.",
    :price 75}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name "Вода \"Байкал\" 0,45 без газа",
    :weight "0,45л",
    :id 6138,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Глубинная вода \"Baikal\" 0,45л. ",
    :price 55}
   {:description
                    "Говядина с овощами, обжаренная в соевом соусе с чесноком и соусом чили.",
    :tags "немного острое",
    :ings
                    "Говядина, перец болгарский, морковь, фасоль стручковая, лук, чеснок, соевый соус, соус чили. Украшение: помидор, огурец, лист салата,укроп.",
    :group "Горячее",
    :c_time "20",
    :short_name " Говядина с овощами ",
    :weight "180/30",
    :id 3835,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Говядина с овощами ",
    :price 120}
   {:description "Мясной фарш с рисом завернутый в капустный лист.",
    :tags "",
    :ings
                 "Говядина,свинина,рис,лук,соль,перец,капуста. Украшение: укроп, лист салата. Соус основной: лук,морковь,чеснок,помидор,томатная паста,укроп,перец чёрный,соль,масло растительное.",
    :group "Горячее",
    :c_time "20",
    :short_name " Голубец ",
    :weight "150/50/10",
    :id 3836,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Голубец ",
    :price 60}
   {:description "Филе горбуши в омлете с томатами",
    :tags "",
    :ings
                 "Горбуша, яйцо, помидор, лук, соль, перец. Украшение: помидор, огурец, лист салата, укроп.",
    :group "Горячее",
    :c_time "20",
    :short_name " Горбуша в бризоле ",
    :weight "110",
    :id 3837,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Горбуша в бризоле ",
    :price 90}
   {:description "-",
    :tags "",
    :ings "",
    :group "Соус",
    :c_time "",
    :short_name " Горчица ",
    :weight "25",
    :id 3854,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Горчица ",
    :price 20}
   {:description "-",
    :tags "",
    :ings "",
    :group "Соус",
    :c_time "",
    :short_name " Горчица ",
    :weight "25",
    :id 1743,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Горчица ",
    :price 20}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Горячий шоколад ",
    :weight "200мл",
    :id 3746,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Горячий шоколад ",
    :price 20}
   {:description "-",
    :tags "",
    :ings "",
    :group "Гарнир",
    :c_time "10",
    :short_name " Гречка ",
    :weight "150",
    :id 3855,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Гречка ",
    :price 45}
   {:description "-",
    :tags "",
    :ings "",
    :group "Гарнир",
    :c_time "10",
    :short_name " Гречка на пару (фитнесс меню)",
    :weight "150",
    :id 6263,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "3",
    :full_name " Гречка на пару (фитнесс меню)",
    :price 45}
   {:description "-",
    :tags "",
    :ings "",
    :group "Соус",
    :c_time "",
    :short_name " Джем в ассортименте ",
    :weight "50",
    :id 3870,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Джем в ассортименте ",
    :price 25}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Долька лимона ",
    :weight "10",
    :id 3748,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Долька лимона ",
    :price 5}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Доставка",
    :weight "-",
    :id 5544,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Доставка",
    :price 0}
   {:description
                    "Кальмар,  тушёный в сливочно-сметанном соусе со свежей морковью и  чёрным перцем",
    :tags "",
    :ings
                    "Кальмар, сливки, сметана, морковь, соль, перец. Украшение: помидор, огурец, лист салата, укроп.",
    :group "Горячее",
    :c_time "20",
    :short_name " Кальмар в сливочно-сметанном соусе ",
    :weight "150",
    :id 3841,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Кальмар в сливочно-сметанном соусе ",
    :price 145}
   {:description
                    "Капучи́но —зерновой кофе \"эспрессо\" с добавлением в него подогретого вспененного молока и нежной пенки.",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Капучино",
    :weight "200мл",
    :id 1641,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Капучино классический",
    :price 90}
   {:description
                    "Отварной картофель, обжаренный в растительном масле с чесноком и укропом",
    :tags "чеснок",
    :ings "картофель, чеснок, укроп, соль",
    :group "Гарнир",
    :c_time "10",
    :short_name " Картофель по-домашнему ",
    :weight "150",
    :id 3856,
    :fractional "Да",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Картофель по-домашнему ",
    :price 45}
   {:description "Золотистый картофель обжареный во фритюре",
    :tags "",
    :ings "",
    :group "Гарнир",
    :c_time "10",
    :short_name " Картофель фри ",
    :weight "150",
    :id 3857,
    :fractional "Да",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Картофель фри ",
    :price 70}
   {:description "-",
    :tags "",
    :ings "",
    :group "Гарнир",
    :c_time "10",
    :short_name " Картофельное пюре ",
    :weight "150",
    :id 3858,
    :fractional "Да",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Картофельное пюре ",
    :price 45}
   {:description "-",
    :tags "",
    :ings "гречка,молоко,вода,соль,сахар.",
    :group "Завтрак",
    :c_time "30",
    :short_name " Каша гречневая ",
    :weight "200",
    :id 6251,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "",
    :full_name " Каша гречневая ",
    :price 80}
   {:description "-",
    :tags "",
    :ings "овсянка,молоко,вода,соль,сахар.",
    :group "Завтрак",
    :c_time "30",
    :short_name " Каша овсяная ",
    :weight "200",
    :id 6252,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "",
    :full_name " Каша овсяная ",
    :price 80}
   {:description "-",
    :tags "",
    :ings "перловка,молоко,вода,соль,сахар.",
    :group "Завтрак",
    :c_time "30",
    :short_name " Каша перловая ",
    :weight "200",
    :id 6253,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "",
    :full_name " Каша перловая ",
    :price 80}
   {:description "-",
    :tags "",
    :ings "рис,молоко,вода,соль,сахар.",
    :group "Завтрак",
    :c_time "30",
    :short_name " Каша рисовая ",
    :weight "200",
    :id 6255,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "",
    :full_name " Каша рисовая ",
    :price 80}
   {:description "",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Квас народный ",
    :weight "200",
    :id 4364,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Квас народный ",
    :price 25}
   {:description "Малосольная кета с репчатым луком.",
    :tags "",
    :ings "Кета, лук, лист салата, соль. ",
    :group "Салаты",
    :c_time "10",
    :short_name " Кета малосольная ",
    :weight "110/30",
    :id 3805,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Кета малосольная ",
    :price 120}
   {:description "-",
    :tags "",
    :ings "",
    :group "Соус",
    :c_time "",
    :short_name " Кетчуп ",
    :weight "",
    :id 3859,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Кетчуп ",
    :price 20}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Кириешки",
    :weight "40",
    :id 3750,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Кириешки пачка ",
    :price 30}
   {:description
                    "Жареные колбаски ручного приготовления из говядины и свинины с приправами.",
    :tags "",
    :ings
                    "Говядина,свинина,перец сладкий,чеснок,соль,паприка. (оболочка натуральная-черева) Украшение: помидор, огурец, лист салата.",
    :group "Горячее",
    :c_time "25",
    :short_name " Колбаски \"Пикантные\"",
    :weight "150/50/10",
    :id 3842,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Колбаски пикантные ",
    :price 150}
   {:description
                    "Жареные колбаски ручного приготовления из говядины и свинины с приправами.",
    :tags "",
    :ings
                    "Говядина,свинина,сало,чеснок,соль,перец чёрный молотый. (оболочка натуральная-черева) Соус: сметана,майонез,,сладкий перец,соль. Украшение: лист салата.",
    :group "Горячее",
    :c_time "25",
    :short_name " Колбаски \"По-домашнему\" ",
    :weight "150/50/10",
    :id 3843,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Колбаски по-домашнему ",
    :price 150}
   {:description "-",
    :tags "",
    :ings
                 "Кольца кальмара в кляре. Соус: соевый соус,соус \"Чили\",крахмал. Украшение:  лист салата.",
    :group "Закуски",
    :c_time "20",
    :short_name " Кольца кальмара ",
    :weight "150/50/10",
    :id 3844,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "1",
    :full_name " Кольца кальмара ",
    :price 110}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Компот ",
    :weight "200мл",
    :id 3753,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Компот ",
    :price 25}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Контейнер РП20 (Платный)",
    :weight "-",
    :id 4372,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Контейнер РП20 (Платный)",
    :price 16}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Коньяк Бастион 0,5л. ",
    :weight "0,5л",
    :id 7239,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Коньяк Бастион 0,5л. ",
    :price 950}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Коньяк Бастион 50мл ",
    :weight "50мл",
    :id 7240,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Коньяк Бастион 50мл ",
    :price 130}
   {:description
                    " Нежнейшая куриная котлета в панировке со сливочным маслом внутри,запечённая во фритюре",
    :tags "",
    :ings
                    "Куриное филе,масло,соль,перец,яйцо,сухари панировочные. Украшение: помидор, огурец, лист салата.",
    :group "Горячее",
    :c_time "20",
    :short_name " Котлета \"По-киевски\"",
    :weight "150/50/30",
    :id 3845,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Котлета по-киевски ",
    :price 145}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Кофе 3 в 1",
    :weight "200мл",
    :id 3754,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Кофе 3 в 1 ",
    :price 20}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Кофе черный ",
    :weight "200мл",
    :id 3755,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Кофе черный ",
    :price 20}
   {:description
                    "Куриные крылышки (3шт),обжаренные во фритюре с фирменным соусом.",
    :tags "",
    :ings
                    "Крыло куриное,соевый соус,чеснок,приправа для курицы. Соус: соевый соус,соус \"Чили\",крахмал. Украшение:  лист салата.",
    :group "Закуски",
    :c_time "25",
    :short_name " Крылья во фритюре ",
    :weight "150/50/10",
    :id 3846,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Крылья во фритюре ",
    :price 150}
   {:description "",
    :tags "",
    :ings "куриное филе,соль.",
    :group "Горячее",
    :c_time "20",
    :short_name " Куринное филе на пару(фитнесс меню) ",
    :weight "200",
    :id 6216,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Куринное филе на пару(фитнесс меню) ",
    :price 180}
   {:description
                    "Куриное филе, обжаренное на сливочном масле с шампиньонами и луком в сливочном соусе",
    :tags "",
    :ings
                    "Куриное филе, шампиньоны, лук, сливки, соль, перец. Украшение: помидор, огурец, лист салата, укроп.",
    :group "Горячее",
    :c_time "20",
    :short_name " Курица в грибном соусе ",
    :weight "160",
    :id 3847,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Курица в грибном соусе ",
    :price 115}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Лимон",
    :weight "10",
    :id 5323,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Лимон",
    :price 5}
   {:description "-",
    :tags "",
    :ings "",
    :group "Соус",
    :c_time "",
    :short_name " Майонез ",
    :weight "50",
    :id 3860,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Майонез ",
    :price 20}
   {:description "-",
    :tags "",
    :ings "",
    :group "Гарнир",
    :c_time "10",
    :short_name " Макароны ",
    :weight "150",
    :id 3861,
    :fractional "Да",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Макароны ",
    :price 45}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Минеральная вода \"Жемчужина Байкала\" 0,5л.",
    :weight "0,5л",
    :id 6137,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Минеральная вода \"Жемчужина Байкала\" 0,5л.",
    :price 45}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Минеральная вода Иркутская 0,6л ",
    :weight "0,6л",
    :id 3756,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Минеральная вода Иркутская 0,6л ",
    :price 60}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Молоко ",
    :weight "20",
    :id 3757,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Молоко ",
    :price 5}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Молочный коктейль Классич. д/5позной",
    :weight "0,5л",
    :id 5858,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Молочный коктейль Классич. д/5позной",
    :price 120}
   {:description "Воздушный коктейль из пломбира с молоком.",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Молочный коктейль классический ",
    :weight "0,5л",
    :id 5109,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Молочный коктейль классический ",
    :price 120}
   {:description
                    "Классический пломбир с добавлением тёртого молочного шоколада.",
    :tags "",
    :ings "Пломбир, молочный шоколад.",
    :group "Десерт",
    :c_time "10",
    :short_name " Мороженое ",
    :weight "90/10",
    :id 3871,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Мороженое ",
    :price 60}
   {:description
                    "Освежающий морс из натуральных ягод брусники,сахара и питьевой воды",
    :tags "",
    :ings "Брусника,сахар,вода.",
    :group "Напитки",
    :c_time "",
    :short_name " Морс брусничный ",
    :weight "200мл",
    :id 3758,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Морс брусничный ",
    :price 25}
   {:description
                    "Освежающий морс из натуральных ягод облепихи,сахара и питьевой воды",
    :tags "",
    :ings "Облепиха,сахар,вода.",
    :group "Напитки",
    :c_time "",
    :short_name " Морс облепиховый ",
    :weight "200мл",
    :id 3759,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Морс облепиховый ",
    :price 25}
   {:description
                    "Освежающий морс из натуральных ягод черники,сахара и питьевой воды",
    :tags "",
    :ings "Черника,сахар,вода",
    :group "Напитки",
    :c_time "",
    :short_name " Морс черничный ",
    :weight "200мл",
    :id 3760,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Морс черничный ",
    :price 25}
   {:description
                    "Свинина, обжаренная в сливочно-сметанном соусе с луком и шампиньонами",
    :tags "",
    :ings
                    "Свинина, шампиньоны, сметана, сливки, лук, соль, перец. Украшение: помидор, огурец, лист салата, укроп.",
    :group "Горячее",
    :c_time "20",
    :short_name " Мясо в сливочно-сметанном соусе ",
    :weight "180/30",
    :id 3848,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Мясо в сливочно-сметанном соусе ",
    :price 150}
   {:description
                    "Свиная отбивная с помидором и шампиньонами, запеченная под сыром с майонезом ",
    :tags "",
    :ings
                    "Свинина, сыр, помидор, шампиньоны, майонез. Украшение: помидор, огурец, лист салата.",
    :group "Горячее",
    :c_time "20",
    :short_name " Мясо по-французски ",
    :weight "180/30",
    :id 3849,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Мясо по-французски ",
    :price 160}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Наполнитель для каши-масло сливочное ",
    :weight "10",
    :id 6247,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Наполнитель для каши-масло сливочное ",
    :price 20}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Наполнитель для каши-мед ",
    :weight "30",
    :id 6248,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Наполнитель для каши-мед ",
    :price 45}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Начинка для яичницы-ветчина ",
    :weight "40",
    :id 6240,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Начинка для яичницы-ветчина ",
    :price 50}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Начинка для яичницы-колбаса п/к ",
    :weight "40",
    :id 6239,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Начинка для яичницы-колбаса п/к ",
    :price 50}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Начинка для яичницы-куринное филе ",
    :weight "40",
    :id 6241,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Начинка для яичницы-куринное филе ",
    :price 40}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Начинка для яичницы-лук пассир. ",
    :weight "40",
    :id 6246,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Начинка для яичницы-лук пассир. ",
    :price 20}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Начинка для яичницы-помидоры",
    :weight "30",
    :id 6245,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Начинка для яичницы-помидоры",
    :price 40}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Начинка для яичницы-сосиски молочн. ",
    :weight "40",
    :id 6242,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Начинка для яичницы-сосиски молочн. ",
    :price 40}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Начинка для яичницы-фасоль стручковая",
    :weight "40",
    :id 6244,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Начинка для яичницы-фасоль стручковая",
    :price 30}
   {:description "",
    :tags "",
    :ings "фасоль,капуста цветная,перец болгарский,кукуруза",
    :group "Гарнир",
    :c_time "20",
    :short_name " Овощи на пару (фитнесс меню) ",
    :weight "150",
    :id 6110,
    :fractional "Да",
    :serving_order3 "2",
    :serving_order4 "3",
    :full_name " Овощи на пару (фитнесс меню) ",
    :price 85}
   {:description
                    "Традиционное блюдо национальной русской кухни, освежающий холодный  суп на домашнем квасе.  Для справки: Окро́шка (от глагола крошить — мелко нареза́ть)",
    :tags "",
    :ings
                    "Квас, говядина, редис,огурец,отварной картофель,яйцо,майонез,хрен, горчица, укром.",
    :group "Супы",
    :c_time "15",
    :short_name " Окрошка ",
    :weight "330",
    :id 3795,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Окрошка ",
    :price 92}
   {:description "-",
    :tags "",
    :ings "яйца,молоко,соль",
    :group "",
    :c_time "10",
    :short_name " Омлет из двух яиц",
    :weight "100",
    :id 6235,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "1",
    :full_name " Омлет из двух яиц",
    :price 90}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Орбит ",
    :weight "",
    :id 3761,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Орбит ",
    :price 35}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Пакет \"С собой\"",
    :weight "-",
    :id 6608,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Пакет \"С собой\"",
    :price 0}
   {:description
                    "Фирменные отварные пельмени ручной лепки. Обьеденье просто. Подаются со сметаной или майонезом на выбор гостя.",
    :tags "",
    :ings "Говядина,свинина,лук,соль,перец,чеснок.",
    :group "Хиты",
    :c_time "20",
    :short_name " Пельмени",
    :weight "160",
    :id 3825,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Пельмени",
    :price 99}
   {:description
                    "Фирменные пельмени ручной лепки,обжаренные во фритюре. Обьеденье просто. Подаются со сметаной или майонезом на выбор гостя.",
    :tags "",
    :ings "Говядина,свинина,лук,соль,перец,чеснок.",
    :group "Хиты",
    :c_time "20",
    :short_name " Пельмени жареные ",
    :weight "160",
    :id 7216,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Пельмени жареные ",
    :price 99}
   {:description
                    "Фирменные пельмени ручной лепки,обжаренные во фритюре. Обьеденье просто. Подаются со сметаной или майонезом на выбор гостя.",
    :tags "",
    :ings "Говядина,свинина,лук,соль,перец,чеснок.",
    :group "Хиты",
    :c_time "20",
    :short_name " Пельмени жареные с майонезом",
    :weight "160/10",
    :id 6467,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Пельмени жареные с майонезом",
    :price 99}
   {:description
                    "Фирменные пельмени ручной лепки,обжаренные во фритюре. Обьеденье просто. Подаются со сметаной или майонезом на выбор гостя.",
    :tags "",
    :ings "Говядина,свинина,лук,соль,перец,чеснок.",
    :group "Хиты",
    :c_time "20",
    :short_name " Пельмени жареные со сметаной ",
    :weight "160/10",
    :id 5662,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Пельмени жареные со сметаной ",
    :price 99}
   {:description
                    "Фирменные отварные пельмени ручной лепки. Обьеденье просто. Подаются со сметаной или майонезом на выбор гостя.",
    :tags "",
    :ings "Говядина,свинина,лук,соль,перец,чеснок.",
    :group "Хиты",
    :c_time "20",
    :short_name " Пельмени с майонезом ",
    :weight "160/10",
    :id 3826,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Пельмени с майонезом ",
    :price 99}
   {:description
                    "Фирменные отварные пельмени ручной лепки. Обьеденье просто. Подаются со сметаной или майонезом на выбор гостя.",
    :tags "",
    :ings "Говядина,свинина,лук,соль,перец,чеснок.",
    :group "Хиты",
    :c_time "20",
    :short_name " Пельмени со сметаной",
    :weight "160/10",
    :id 3827,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Пельмени со сметаной",
    :price 99}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Пиво Козел светлое бут.0,5л.",
    :weight "0,5л",
    :id 5315,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Пиво Козел светлое бут.0,5л.",
    :price 115}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Пиво Козел темное бут. 0,5 ",
    :weight "0,5л",
    :id 5316,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Пиво Козел темное бут. 0,5 ",
    :price 115}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Пиво Пекин  0,63л ",
    :weight "0,63л",
    :id 5647,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Пиво Пекин  0,63л ",
    :price 315}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Пиво Сибирская корона розл. 0,5л. ",
    :weight "0,5л",
    :id 3773,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Пиво Сибирская корона розл. 0,5л. ",
    :price 120}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Пиво Туборг светл.0,5л ",
    :weight "0,5л",
    :id 3774,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Пиво Туборг светл.0,5л ",
    :price 110}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Пиво Хайнекен светлое 0,5л ",
    :weight "0,5л",
    :id 3775,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Пиво Хайнекен светлое 0,5л ",
    :price 140}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Пиво Харбин 1900  0,5л ",
    :weight "0,5л",
    :id 5650,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Пиво Харбин 1900  0,5л ",
    :price 350}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Пиво Хольстен 0,5л ",
    :weight "0,5л",
    :id 3776,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Пиво Хольстен 0,5л ",
    :price 120}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Пиво черниговское НЕФИЛЬТРОВ.розл. 0,5л.",
    :weight "0,5л",
    :id 5320,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Пиво черниговское НЕФИЛЬТРОВ.розл. 0,5л.",
    :price 110}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Пиво черниговское фильтрованное.розл. 0,5л.",
    :weight "0,5л",
    :id 7248,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Пиво черниговское фильтрованное.розл. 0,5л.",
    :price 110}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Пиво Чингисхан 0,45л ",
    :weight "0,45л",
    :id 5652,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Пиво Чингисхан 0,45л ",
    :price 275}
   {:description "-",
    :tags "",
    :ings "",
    :group "Десерты",
    :c_time "10",
    :short_name " Пирожное \"Медовое\" ",
    :weight "100",
    :id 4719,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Пирожное \"Медовое\" ",
    :price 65}
   {:description "-",
    :tags "",
    :ings "",
    :group "Десерты",
    :c_time "10",
    :short_name " Пирожное \"Персиковое\" ",
    :weight "100",
    :id 4720,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Пирожное \"Персиковое\" ",
    :price 65}
   {:description "-",
    :tags "",
    :ings "",
    :group "Десерты",
    :c_time "10",
    :short_name " Пирожное \"Черёмуховое\" ",
    :weight "100",
    :id 4721,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Пирожное \"Черёмуховое\" ",
    :price 65}
   {:description "-",
    :tags "",
    :ings "",
    :group "Десерты",
    :c_time "",
    :short_name "Кит Кат 45гр",
    :weight "45",
    :id 3778,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Плитка Кит Кат 45гр ",
    :price 0}
   {:description
                    "Фирменные горячие и острые позы с соком внутри для любителей острого. (специально разработаный состав с добавалениям острых специй)",
    :tags "",
    :ings
                    "Говядина,свинина,сало,лук,соль,перец чёрный молотый,капуста ким-чи",
    :group "Хиты",
    :c_time "25",
    :short_name " Поза восточная ",
    :weight "75",
    :id 3829,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Поза восточная ",
    :price 42}
   {:description "Классические фирменные горячие позы с соком внутри.",
    :tags "",
    :ings "Говядина,свинина,сало,лук,соль,перец чёрный молотый",
    :group "Хиты",
    :c_time "25",
    :short_name " Поза классическая ",
    :weight "75",
    :id 3828,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Поза классическая ",
    :price 42}
   {:description
                    "Фирменные горячие позы с рубленым фаршем из трёх видов мяса свинины, говядины и баранины, с соком внутри.",
    :tags "",
    :ings
                    "Говядина,свинина,сало,лук,соль,перец чёрный молотый,капуста ким-чи",
    :group "Хиты",
    :c_time "25",
    :short_name " Поза рубленая ",
    :weight "75",
    :id 3830,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Поза рубленая ",
    :price 53}
   {:description "-",
    :tags "",
    :ings "",
    :group "Гарнир",
    :c_time "25",
    :short_name " Рис на пару (фитнесс меню)",
    :weight "150",
    :id 6262,
    :fractional "Да",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Рис на пару (фитнесс меню)",
    :price 45}
   {:description "Отварной рис с овощами.",
    :tags "",
    :ings
                 "Отварной рис,зелёный горошек,консервированная кукуруза,сладкий перец,морковь.",
    :group "Гарнир",
    :c_time "10",
    :short_name " Рис с овощами ",
    :weight "150",
    :id 3863,
    :fractional "Да",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Рис с овощами ",
    :price 45}
   {:description
                    "Традиционное блюдо китайской кухни. Можно употреблять как гарнир и как отдельное блюдо.",
    :tags "",
    :ings "рис,соевый соус,яйцо.",
    :group "Гарнир",
    :c_time "10",
    :short_name " Рис с яйцом ",
    :weight "150",
    :id 6108,
    :fractional "Да",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Рис с яйцом ",
    :price 45}
   {:description "-",
    :tags "",
    :ings "",
    :group "Алкоголь",
    :c_time "",
    :short_name " Российское шампанское Ариант бел. п/сл. 0,75",
    :weight "0,75л",
    :id 6201,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Российское шампанское Ариант бел. п/сл. 0,75 ",
    :price 350}
   {:description
                    "Филе горбуши на подушке из отварного картофеля и лука, запеченное под сыром с майонезом",
    :tags "",
    :ings
                    "Горбуша, отварной картофель, лук, сыр, майонез, соль, перец. Украшение: помидор, огурец, лист салата, укроп.",
    :group "Горячее",
    :c_time "20",
    :short_name " Рыба по-русски",
    :weight "180",
    :id 3850,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Рыба по-русски",
    :price 115}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " С собой ",
    :weight "-",
    :id 3876,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " С собой ",
    :price 0}
   {:description
                    "Классический салат из свежих овощей и сыра «Фета», заправленный растительным маслом",
    :tags "",
    :ings
                    "огурец, помидор, болгарский перец, маслины, лист салата, сыр «Фета», растительное масло",
    :group "Салаты",
    :c_time "10",
    :short_name "Греческий ",
    :weight "120",
    :id 3803,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат греческий ",
    :price 74}
   {:description
                    "Салат из копченой колбасы, сыра и огурца, заправленный майонезом.",
    :tags "",
    :ings "колбаса п/к, огурец, сыр, майонез",
    :group "Салаты",
    :c_time "10",
    :short_name "Закусочный ",
    :weight "120",
    :id 3804,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат закусочный ",
    :price 74}
   {:description
                    "Острый корейский салат из свежей моркови с соусом чим-чим",
    :tags "немного острое",
    :ings "морковь, соус «чим-чим».",
    :group "Салаты",
    :c_time "10",
    :short_name "Морковь по-корейски ",
    :weight "90",
    :id 3806,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат Морковь по-корейски ",
    :price 60}
   {:description
                    "Салат из кусочков малосолёной кеты, отварного картофеля и моркови под майонезом и тёртым отварным яйцом",
    :tags "",
    :ings "филе кеты, картофель, морковь, яйцо, майонез, укроп",
    :group "Салаты",
    :c_time "10",
    :short_name "Норвежский ",
    :weight "120",
    :id 3808,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат норвежский ",
    :price 84}
   {:description
                    "Лёгкий салат из свежих овощей, заправленный растительным маслом",
    :tags "",
    :ings
                    "огурец, помидор, болгарский перец, лист салата, укроп, растительное масло",
    :group "Салаты",
    :c_time "10",
    :short_name "Овощной ",
    :weight "120",
    :id 3809,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат овощной ",
    :price 74}
   {:description "Салат из свежих овощей",
    :tags "",
    :ings "огурец, помидор, болгарский перец, лист салата, укроп",
    :group "",
    :c_time "10",
    :short_name "Овощной без масла и соли (фитнесс меню)",
    :weight "130",
    :id 6232,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат овощной без масла и соли (фитнесс меню)",
    :price 70}
   {:description "Классический салат \"Оливье\" с куриным филе",
    :tags "",
    :ings
                 "куриное филе, картофель, морковь, яйцо, консервированный горошек, огурец, майонез, укроп",
    :group "Салаты",
    :c_time "10",
    :short_name "Оливье ",
    :weight "120",
    :id 3810,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат оливье ",
    :price 84}
   {:description
                    "Салат из отварного куриного филе со свежим помидором, сыром и грецким орехом, заправленный  майонезом",
    :tags "",
    :ings "куриное филе, помидор, грецкий орех, сыр, майонез",
    :group "Салаты",
    :c_time "10",
    :short_name "Птичка ",
    :weight "120",
    :id 3807,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат птичка ",
    :price 74}
   {:description
                    "Салат из тёртой отварной свеклы со свежим чесноком и тёртым сыром, заправленный майонезом",
    :tags "",
    :ings "свёкла, чеснок, сыр, майонез, соль",
    :group "Салаты",
    :c_time "10",
    :short_name "Свекольный ",
    :weight "150",
    :id 6106,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат свекольный ",
    :price 95}
   {:description
                    "Салат из куриного филе, крабовых палочек со свежим огурцом, листом салата и кириешками, заправленный майонезом",
    :tags "",
    :ings
                    "куриное филе, крабовые палочки, огурец, кириешки, лист салата, соль",
    :group "Салаты",
    :c_time "10",
    :short_name "Три корочки",
    :weight "120",
    :id 3811,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат три корочки",
    :price 74}
   {:description
                    "Салат из копчёного куриного филе с ананасом и обжаренными шампиньонами, заправленный майонезом",
    :tags "",
    :ings
                    "копчёное куриное филе, консервированный ананас, шампиньоны, майонез",
    :group "Салаты",
    :c_time "10",
    :short_name "Французский",
    :weight "120",
    :id 3812,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат французский",
    :price 95}
   {:description
                    "Салат из отварного кальмара, крабовых палочек и красной икры со свежим огурцом и отварным яйцом, заправленный майонезом",
    :tags "",
    :ings
                    "кальмар, крабовые палочки, икра красная, огурец, яйцо, майонез",
    :group "Салаты",
    :c_time "10",
    :short_name "Царский ",
    :weight "120",
    :id 3813,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат царский ",
    :price 120}
   {:description "Классический салат «Цезарь» со малосольной кетой",
    :tags "",
    :ings
                 "кета, помидор, лист салата, сухарики, сыр «Пармезан», соус «Цезарь». Соус: дижонская горчица, соевый соус, чеснок, майонез",
    :group "Салаты",
    :c_time "10",
    :short_name "Цезарь с кетой ",
    :weight "150",
    :id 3814,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат Цезарь с кетой ",
    :price 120}
   {:description "Классический салат «Цезарь» с курицей",
    :tags "",
    :ings
                 "куриное филе, помидор, лист салата, сухарики, сыр «Пармезан», соус «Цезарь». Соус: дижонская горчица, соевый соус, чеснок, майонез",
    :group "Салаты",
    :c_time "10",
    :short_name "Цезарь с курицей ",
    :weight "150",
    :id 3815,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Салат Цезарь с курицей ",
    :price 110}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Сахар ",
    :weight "8",
    :id 3780,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Сахар ",
    :price 3}
   {:description "-",
    :tags "",
    :ings "",
    :group "Соус",
    :c_time "",
    :short_name " Сгущенка ",
    :weight "50",
    :id 3864,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Сгущенка ",
    :price 20}
   {:description "-",
    :tags "",
    :ings "",
    :group "Соус",
    :c_time "",
    :short_name " Сметана ",
    :weight "50",
    :id 3865,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Сметана ",
    :price 25}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Сок в ассортименте ",
    :weight "200мл",
    :id 3782,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Сок в ассортименте ",
    :price 30}
   {:description
                    "Классическая солянка из трёх видах мяса с  маринованным огурчиком, парой маслин и долькой лимона, заправленная по желанию гостя сметаной или майонезом",
    :tags "",
    :ings
                    "копчёные свиные рёбра, колбаса п/к, ветчина, сосиски молочные, томатная паста, картофель, маринованные огурцы, лук, маслины, лимон, укроп, соль, перец, сметана или майонез",
    :group "Супы",
    :c_time "15",
    :short_name " Солянка ",
    :weight "330",
    :id 5106,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Солянка ",
    :price 112}
   {:description
                    "Классическая солянка из трёх видах мяса с  маринованным огурчиком, парой маслин и долькой лимона, заправленная по желанию гостя сметаной или майонезом",
    :tags "",
    :ings "",
    :group "Супы",
    :c_time "15",
    :short_name " Солянка с майонезом",
    :weight "330/20",
    :id 3796,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Солянка с майонезом",
    :price 112}
   {:description
                    "Классическая солянка из трёх видах мяса с  маринованным огурчиком, парой маслин и долькой лимона, заправленная по желанию гостя сметаной или майонезом",
    :tags "",
    :ings "",
    :group "Супы",
    :c_time "15",
    :short_name " Солянка со сметаной ",
    :weight "330/20",
    :id 3797,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Солянка со сметаной ",
    :price 112}
   {:description
                    "Обжаренное куриное филе в сливках с овощами и кукурузой",
    :tags "",
    :ings
                    "Куриное филе, перец болгарский, кукуруза консервированная, лук, сливки, соль, перец. Украшение: помидор, огурец, лист салата, укроп.",
    :group "Горячее",
    :c_time "20",
    :short_name " Соте из курицы ",
    :weight "160",
    :id 3851,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Соте из курицы ",
    :price 110}
   {:description "-",
    :tags "",
    :ings "",
    :group "Соус",
    :c_time "",
    :short_name " Соус острый ",
    :weight "50",
    :id 3866,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Соус острый ",
    :price 20}
   {:description "-",
    :tags "",
    :ings "Филе кеты,соль",
    :group "",
    :c_time "20",
    :short_name " Стейк из кеты на пару (фитнесс меню)",
    :weight "200",
    :id 6217,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Стейк из кеты на пару (фитнесс меню)",
    :price 285}
   {:description "Лёгкий суп на бульоне из курицы с  яичной лапшой",
    :tags "",
    :ings "куриное филе, лапша яичная, морковь, лук, укроп, соль, перец",
    :group "Супы",
    :c_time "15",
    :short_name " Суп-лапша",
    :weight "350",
    :id 3798,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Суп-лапша куриный ",
    :price 84}
   {:description "-",
    :tags "",
    :ings "Хлеб ржаной,паприка,чеснок,соль,масло растительное",
    :group "Закуски",
    :c_time "10",
    :short_name " Сухарики к пиву ",
    :weight "100",
    :id 3783,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Сухарики к пиву ",
    :price 50}
   {:description
                    "Традиционный русский десерт из домашнего творога с добавлением изюма,  обжаренный до румяной корочки во фритюре. Для иностранцев: Russian cheesecake - \"русский чизкейк\"",
    :tags "",
    :ings "творог, изюм, яйцо куриное, манка, сахар, ванилин",
    :group "Десерты",
    :c_time "10",
    :short_name " Сырники с изюмом ",
    :weight "120",
    :id 3831,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Сырники с изюмом ",
    :price 75}
   {:description
                    "Нежнейшая запеченная котлета из кеты, помидора и лука с соусом «Тар-Тар»",
    :tags "",
    :ings
                    "Кета, помидор, лук, мука, укроп, соль, перец. Соус: сметана, огурцы маринованные, чеснок, укроп, соль, перец. Украшение:  лист салата, лимон, маслины.",
    :group "Горячее",
    :c_time "20",
    :short_name " Тар-тар из кеты ",
    :weight "350",
    :id 3840,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Тар-тар из кеты ",
    :price 155}
   {:description "Запечённые под соусом шарики из мясного фарша",
    :tags "",
    :ings
                 "Говядина,свинина,рис,яйцо,соль,перец. Соус: томатная паста,шампиньоны,морковь,лук,чеснок,соль,перец. Украшение: помидор, огурец, лист салата,укроп.",
    :group "Горячее",
    :c_time "20",
    :short_name " Тефтели ",
    :weight "130/50/30",
    :id 3852,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Тефтели ",
    :price 95}
   {:description "Уха из кеты ",
    :tags "",
    :ings "кета, картофель, морковь, лук, укроп, соль, перец",
    :group "Супы",
    :c_time "15",
    :short_name " Уха из кеты ",
    :weight "330",
    :id 3799,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Уха из кеты ",
    :price 74}
   {:description "-",
    :tags "",
    :ings "",
    :group "Гарнир",
    :c_time "10",
    :short_name " Фасоль отварная(фитнесс меню)",
    :weight "150",
    :id 6264,
    :fractional "Да",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Фасоль отварная(фитнесс меню)",
    :price 85}
   {:description "Фасоль с чесноком,обжаренная на растительном масле.",
    :tags "",
    :ings "Фасоль,чеснок,соль,растительное масло.",
    :group "Гарнир",
    :c_time "10",
    :short_name " Фасоль с чесноком ",
    :weight "150",
    :id 3869,
    :fractional "Да",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Фасоль с чесноком ",
    :price 85}
   {:description
                    "Национальный грузинский суп из говядины с рисом и чесноком",
    :tags "",
    :ings
                    "говядина, томатная паста, соус чили, чеснок, лук, рис, укроп, хмели-сунели, соль, перец",
    :group "Супы",
    :c_time "15",
    :short_name " Харчо ",
    :weight "330",
    :id 3800,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Харчо ",
    :price 105}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Хлеб ",
    :weight "20",
    :id 3786,
    :fractional "Нет",
    :serving_order3 "1",
    :serving_order4 "1",
    :full_name " Хлеб ",
    :price 3}
   {:description
                    "Черный чай. Чай Ассам легко определить по специфическому, пряному, немного цветочному аромату с необычными для чёрного чая медовыми нотками",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Чай \"Ассам\"",
    :weight "1л/0,5л",
    :id 5260,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Чай \"Ассам\"",
    :price 70}
   {:description
                    "Сорт зелёного чая. Чай Сенча обладает изысканным терпким вкусом с легкой горчинкой и отчетливыми свежими травяными и ореховыми нотками.",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Чай \"Сенча\"",
    :weight "1л/0,5л",
    :id 5262,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Чай \"Сенча\"",
    :price 70}
   {:description
                    "Чёрный чай с добавлением масла из кожуры плодов бергамота. ",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Чай \"Эрл Грей\" ",
    :weight "1л/0,5л",
    :id 5261,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Чай \"Эрл Грей\" ",
    :price 70}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Чай гринфилд зеленый ",
    :weight "200мл",
    :id 5321,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Чай гринфилд зеленый ",
    :price 14}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Чай гринфилд красный ",
    :weight "200мл",
    :id 5267,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Чай гринфилд красный ",
    :price 14}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Чай гринфилд черный ",
    :weight "200мл",
    :id 5282,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Чай гринфилд черный ",
    :price 14}
   {:description "Белый чай со вкусом жасмина.",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Чай жасминовый \"Бай Хао\" ",
    :weight "1л/0,5л",
    :id 5263,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Чай жасминовый \"Бай Хао\" ",
    :price 70}
   {:description "-",
    :tags "",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Чай Фруктовый \"Черешневый\" ",
    :weight "1л/0,5л",
    :id 5264,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Чай Фруктовый \"Черешневый\" ",
    :price 70}
   {:description
                    "Наш фирменный хрустящий и сочный чебурек из трёх видов мяса с луком и специями,обжаренный во фритюре до золотистой корочки и, обязательно, с соком внутри. Пальчики оближете!",
    :tags "",
    :ings "Говядина,свинина,баранина,лук,соль,перец.",
    :group "Хиты",
    :c_time "20",
    :short_name " Чебурек с мясом ",
    :weight "120",
    :id 3832,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Чебурек с мясом ",
    :price 60}
   {:description
                    "Наш фирменный хрустящий и сочный чебурек из трёх видов мяса и сыра,обжаренный во фритюре до золотистой корочки и, обязательно, с соком внутри. Пальчики оближете!",
    :tags "",
    :ings "Говядина,свинина,баранина,сыр,лук,соль,перец.",
    :group "Хиты",
    :c_time "20",
    :short_name " Чебурек с мясом и сыром ",
    :weight "140",
    :id 3833,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "2",
    :full_name " Чебурек с мясом и сыром ",
    :price 65}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Чемпионат 5 поз ",
    :weight "-",
    :id 6250,
    :fractional "Нет",
    :serving_order3 "",
    :serving_order4 "",
    :full_name " Чемпионат 5 поз ",
    :price 0}
   {:description
                    "Шницель из свиного фарша в панировке,обжаренный до хрустящей корочки.",
    :tags "",
    :ings
                    "Свинина,лук,соль,перец,сухари панировочные. Соус: томатная паста,шампиньоны,морковь,лук,чеснок,соль,перец. Украшение: помидор, огурец, лист салата, укроп.",
    :group "Горячее",
    :c_time "20",
    :short_name " Шницель свиной ",
    :weight "120/50/30",
    :id 3853,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "3",
    :full_name " Шницель свиной ",
    :price 130}
   {:description "-",
    :tags "",
    :ings "",
    :group "Десерты",
    :c_time "",
    :short_name " Шоколад 100гр",
    :weight "100",
    :id 3788,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Шоколад 100гр",
    :price 80}
   {:description "-",
    :tags "",
    :ings "",
    :group "Десерты",
    :c_time "",
    :short_name " Шоколад 25гр ",
    :weight "25",
    :id 3790,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Шоколад 25гр ",
    :price 35}
   {:description "-",
    :tags "",
    :ings "",
    :group "",
    :c_time "",
    :short_name " Шоколад тертый ",
    :weight "10",
    :id 3872,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Шоколад тертый ",
    :price 10}
   {:description "Крепкий классический зерновой кофе.",
    :tags "40мл",
    :ings "",
    :group "Напитки",
    :c_time "",
    :short_name " Эспрессо ",
    :weight "40мл",
    :id 5488,
    :fractional "Нет",
    :serving_order3 "3",
    :serving_order4 "4",
    :full_name " Эспрессо ",
    :price 70}
   {:description "-",
    :tags "",
    :ings "яйцо,соль,масло растительное",
    :group "Завтрак",
    :c_time "10",
    :short_name " Яичница из двух яиц ",
    :weight "100",
    :id 6233,
    :fractional "Нет",
    :serving_order3 "2",
    :serving_order4 "",
    :full_name " Яичница из двух яиц ",
    :price 70}])